# Generated by Django 5.0.7 on 2024-07-25 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateTimeField(default=django.utils.timezone.now)),
                ('tea_type', models.CharField(choices=[('ST', 'Sex Tea'), ('PST', "Tea with angela white and ava addams's squirt"), ('NL', 'Normal tea'), ('SL', 'Normal tea')], max_length=3)),
            ],
        ),
    ]
