# Generated by Django 5.0.7 on 2024-07-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='image',
            field=models.ImageField(default=1, upload_to='chais/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
